### PR TITLE
Issue547

### PR DESCRIPTION
**Pull request by teravest**
I broke github and had to delete my branch and reupload it.

### CODE REVIEW

**Comment by teravest** [comment]
I think @adamrp said before this gets merged we should all test it together. I think everyone is back next week.  It would be good to get this merged.

**Comment by ElDeveloper** [comment]
Sounds good.

**Comment by wasade** [comment]
Agree, sounds good. Monday?

**Comment by ElDeveloper** [comment]
Can't make it on monday though :S

Thanks!

Yoshiki.

2013/12/27 Daniel McDonald notifications@github.com

**Comment by teravest** [comment]
Is everyone going to be in on Tuesday?

**Comment by wasade** [comment]
I'll be in

**Comment by ElDeveloper** [comment]
I won't.

Yoshiki Vázquez-Baeza

**Comment by teravest** [comment]
If @adamrp will be in I can go over it tomorrow with @wasade and @adamrp  and show @ElDeveloper when he gets back from vacation.

**Comment by ElDeveloper** [comment]
Sounds good.

**Comment by adamrp** [comment]
I don't remember commenting on this pull request previously (although i probably just forgot), but i will be in tomorrow afternoon anyhow to have a look!

**Comment by teravest** [comment]
@adamrp we talked about it in person. See you tomorrow

**Comment by teravest** [comment]
Some how pull request reverts all the changes, i need to fix that today....

**Pull request merged**
