### PR TITLE
few more accessions

### PR DESCRIPTION
**Pull request by wasade**
Needs to sit a few days as rounds 4/5 are still in processing at EBI. Thanks @adamrp for getting these submitted!

### CODE REVIEW

**Comment by rob-knight** [comment]
Yes thanks! When do results go out to participants? Many are getting anxious etc.

On Mar 19, 2014, at 3:18 PM, "Daniel McDonald" <notifications@github.com<mailto:notifications@github.com>> wrote:

Needs to sit a few days as rounds 4/5 are still in processing at EBI. Thanks @adamrphttps://github.com/adamrp for getting these submitted!

---

You can merge this Pull Request by running

  git pull https://github.com/wasade/qiime_web_app more_accs

Or view, comment on, or merge it at:

  https://github.com/qiime/qiime_web_app/pull/648

Commit Summary
-   few more accessions

File Changes
-   M www/americangut/FAQ.psphttps://github.com/qiime/qiime_web_app/pull/648/files#diff-0 (4)

Patch Links:
-   https://github.com/qiime/qiime_web_app/pull/648.patch
-   https://github.com/qiime/qiime_web_app/pull/648.diff

**Comment by wasade** [comment]
currently fixing bugs

**Comment by wasade** [comment]
@adamrp @ElDeveloper @teravest, possible to get this live soon?

**Comment by adamrp** [comment]
@wasade, We'll be doing a deploy in about an hour

**Pull request merged**
