### PR TITLE
show project type of the barcode in barcode_util

### PR DESCRIPTION
**Pull request by RNAer**
database/procedures/get_barcode_proj_type.sql needs to be deployed to beast.

### CODE REVIEW

**Comment by wasade** [comment]
Thanks Zech. Possible to have this in a larger font, or someway to draw more attention to it? I really like how this is not specific to, say, functional feces but is instead general to the project. This means that even if we scan ICU microbiome samples, it will flag it.

**Comment by RNAer** [comment]
sure. totally agree on the generality.

It seems quarterbarrel is down? I can't login it.

**Comment by wasade** [comment]
Yes, @douginator2000 can you comment on qb please?

**Comment by douginator2000** [comment]
It's back up, though the database contents had to be reverted to ~2 days
ago. If you have changes to the schema, you may need to re-deploy them for
testing.

On Thu, Sep 19, 2013 at 11:36 AM, Daniel McDonald
notifications@github.comwrote:

> Yes, @douginator2000 https://github.com/douginator2000 can you comment
> on qb please?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/516#issuecomment-24758292
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
Hey, just checked this with @Adamrp and I think Daniel's suggestion makes a lot of sense, if the "Project Type" can be a little more 'evident' that would be fantastic i. e. maybe before the "Barcode" sign? so that it read:

```
American Gut Project
Barcode
000000001
Missing Info
```

instead of:

```
Barcode
000000001
Missing Info
```

**Comment by RNAer** [comment]
it does that.

**Comment by adamrp** [comment]
Do you have a more recent version of the code that you haven't pushed to this branch yet?  I am seeing the project title displayed below the colored box that details the barcode status.  I think what Yoshiki is saying is that the Project Title should be the first line _in_ the colored box.

**Comment by RNAer** [comment]
I see. I have updated code to highlight it as standalone instead of as part of the color stamp. up to discussion, though.

**Comment by adamrp** [comment]
I'd be happy to take a look if you push it to the branch associated with this pull request -- or is it under a different branch?

**Comment by RNAer** [comment]
surely I can push into the same pull request and deploy it on webdev if
you're done with your webdev branch.

**Comment by adamrp** [comment]
I am done with my webdev branch -- sorry for leaving it checked out -- or I can just use my virtual box; either way works for me!

**Comment by RNAer** [comment]
done. it's live on webdev too.

**Comment by adamrp** [comment]
I still think it would be better as the first line, bolded, in the colored box.

**Comment by RNAer** [comment]
ok. it's changed on webdev

**Comment by adamrp** [comment]
Thanks a lot, Zech, this looks great!  Sorry to be nitpicky, merging now.

**Pull request merged**
