### PR TITLE
fixing datepicker stuff

### PR DESCRIPTION
**Pull request by megalodonatron**
fixes issue #289 Also some consent form updates snuck in there

### CODE REVIEW

**Comment by ElDeveloper** [comment]
The only thing that I noticed is that the hour entry in "Add sample" does not validate for letters or only numbers i. e. I was able to input this: `l33t l1f3` without a problem.

Also, I noticed that the date entry would allow me to enter `123123123123123123123` and take that as an input. 

---

I made sure to open and modify the files in the VirtualBox to avoid one of those _funny_ virtual box bugs. Though let me know if I should be seeing something different so I make sure I re-check it.

**Comment by megalodonatron** [comment]
Ok I'll add some validation for those fields

**Comment by douginator2000** [comment]
Has someone attempted to submit different date formats and see what happens in the database?

**Comment by megalodonatron** [comment]
It only validates if you do mm/dd/yyyy, anything else turns red.

**Comment by douginator2000** [comment]
The tricky thing will be international users who will reverse the day/month
from the US format.

On Thu, Apr 4, 2013 at 2:06 PM, Meg Pirrung notifications@github.comwrote:

> It only validates if you do mm/dd/yyyy, anything else turns red.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/304#issuecomment-15920517
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
There's an example next to it that says mm/dd/yyyy, so I don't know if we can do any more than that :rabbit:

**Comment by ElDeveloper** [comment]
We shouldn't, or I think there's no need to. Is there a validation in place to guarantee that the first two numbers are not greater than 12?

Yoshiki.

**Comment by megalodonatron** [comment]
Yes it prevents > 12 in the month area

**Comment by megalodonatron** [comment]
It even is smart enough to figure out if the month has 30 or 31 days and prevents 31 if the month only has 30

**Pull request merged**
