### PR TITLE
Fixes #587

### LINKED ISSUE #587: Make it easier to view results
I had 2 emails on the help account about viewing results today.  The barcode number is a link but it is not link formatted.  It is just plain text.  Making the barcode look like a link will ease some confusion.

### PR DESCRIPTION
**Pull request by teravest**
The barcode link is now a button.  I think this will make
it more obvious for users that this is a way to see the
barcode information.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Code looks good, would you mind deploying this on webdev?

**Comment by teravest** [comment]
Done!

**Comment by ElDeveloper** [comment]
Tested against:

OSX 10.9.1:
- Safari 7.0.1
- Firefox 26.0
- Opera 12.6
- Chrome 32.0.1700.77

Windows XP:
- Firefox 23.0.1
- Chrome 32.0.1700.6 m

**Comment by ElDeveloper** [comment]
Thanks @teravest

**Comment by wasade** [comment]
Awesome, thanks @teravest!

**Pull request merged**
