### PR TITLE
Pull and dump verification codes for bulk emailing

### PR DESCRIPTION
**Pull request by wasade**

### CODE REVIEW

**Comment by douginator2000** [comment]
Should probably go in the Scripts directory. Anyone know if the file path can be changed on GitHub?

**Comment by ElDeveloper** [comment]
I think it can 

https://github.com/blog/1436-moving-and-renaming-files-on-github

**Comment by douginator2000** [comment]
I don't think anyone but the code owner has the ability to change locations. Daniel, can you move this to a python_code/scripts directory and re-submit?

**Comment by ElDeveloper** [comment]
Yup. totally right.

**Comment by wasade** [comment]
ya, will do in a little

**Comment by douginator2000** [comment]
Thanks sir.

On Mon, Apr 1, 2013 at 12:20 PM, Daniel McDonald
notifications@github.comwrote:

> ya, will do in a little
> 
> On Mon, Apr 1, 2013 at 12:19 PM, Doug Wendel notifications@github.comwrote:
> 
> > I don't think anyone but the code owner has the ability to change
> > locations. Daniel, can you move this to a python_code/scripts directory
> > and
> > re-submit?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/pull/272#issuecomment-15728523>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/272#issuecomment-15728590
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by wasade** [comment]
:cake:

**Comment by douginator2000** [comment]
The cake is a lie

On Sun, Apr 7, 2013 at 1:13 PM, Daniel McDonald notifications@github.comwrote:

> [image: :cake:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/272#issuecomment-16021420
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
:+1:

**Pull request merged**
