### PR TITLE
fix#540  This passes the study_id in the form

### PR DESCRIPTION
**Pull request by teravest**
```
when editing a study, instead of collecting it from the
session. The study_id remains in the session so everything else
functions the same.  It is just added to the form and used from
the form when editing an existing study.
I tested by selecting a study "emily_test" study_id 2114
clicked on edit study
opened a second tab and logged in
selected study "emily_test_2" study_id 2134
went back to the first tab and edited the study.
Then I checked the database and the correct study was edited.
```

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Great to see this @teravest, this is something that we need so badly! Add another virtual :beer: to your account! Should this go in before/after or aside from #541? Or do we want to completely close that.

**Comment by teravest** [comment]
I think that #541 should be closed and this should go in instead.
While #541 is a good idea, it is too disruptive to general use, and this
solves the problem without being disruptive.

**Comment by ElDeveloper** [comment]
Sounds good. Agreed on it being too disruptive. @adamrp and I should test this and then meet to deploy these changes sometime next week.

**Comment by teravest** [comment]
Hopefully we can get @adamrps metadata change in too, and my add kit to
project change

**Comment by adamrp** [comment]
This all sounds good to me!  I'll test shortly.

**Comment by adamrp** [comment]
FYI, I'm going to deploy this to webdev now.

**Comment by adamrp** [comment]
Excellent! This works, and I have no further comments on the code.  Thanks so much @teravest

**Comment by ElDeveloper** [comment]
This looks good! I noticed however that we still have the problem where having the two tabs in a single browser will make the study identifier be shared by both tabs i. e. if I open study 1 in tab A and study 2 in tab B and then reload tab A and then tab B both will have study identifier equal to 2.

I'm beginning to think that the easiest way might be to have the study identifier be part of the GET variables.

**Comment by adamrp** [comment]
We might be able to do that, but could open security issues unless we
aggressively check for study ownership and permissions on basically every
page, right?

**Comment by adamrp** [comment]
Also, i think the issue that @teravest was trying to solve here was the
overwriting of data, which should now be impossible (at least, through the
"edit study info" link -- not sure what happens if you try to upload
metadata or sequences in one tab after you open up another tab and select a
different study...)

**Comment by ElDeveloper** [comment]
@adamrp you are right about both security and the goal of this pull request. I've tested this and seems to be working great. Unless someone opposes, we should merge this.

**Comment by teravest** [comment]
Can you merge this one now?

**Comment by ElDeveloper** [comment]
t0klc0c

**Pull request merged**
