### PR TITLE
Adding twitter control, moved map key to bottom left, other misc. aesthetic updates

### PR DESCRIPTION
**Pull request by douginator2000**

### CODE REVIEW

**Comment by douginator2000** [comment]
Available on webdev at the moment as well for preview. Must log in to see twitter control.

**Comment by ElDeveloper** [comment]
:+1: LOOKS AWESOME!

**Comment by ElDeveloper** [comment]
Only thing, could we make it available from the main web page? i. e. somewhere in the log-in page?

**Comment by douginator2000** [comment]
I played around with it on that page as well... I'll toss it back up there
and let's figure out a good place for it such that it doesn't look al
strange.

On Mon, Apr 29, 2013 at 2:27 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> Only thing, could we make it available from the main web page? i. e.
> somewhere in the log-in page?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/382#issuecomment-17191963
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
Cool thanks Señor Developer!

**Comment by douginator2000** [comment]
Deployed to webdev - note that the control doesn't exactly track the margin
from the header (one is absolute, one is a percentage), but you can
basically see what it looks like. Thoughts on a better place to put it? It
looks bad IMO.

On Mon, Apr 29, 2013 at 2:41 PM, Yoshiki Vázquez Baeza <
notifications@github.com> wrote:

> Cool thanks Señor Developer!
> 
> El 29/04/2013, a las 14:40, Doug Wendel notifications@github.com
> escribió:
> 
> > I played around with it on that page as well... I'll toss it back up
> > there
> > and let's figure out a good place for it such that it doesn't look al
> > strange.
> > 
> > On Mon, Apr 29, 2013 at 2:27 PM, Yoshiki Vázquez Baeza <
> > notifications@github.com> wrote:
> > 
> > > Only thing, could we make it available from the main web page? i. e.
> > > somewhere in the log-in page?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/qiime/qiime_web_app/pull/382#issuecomment-17191963>
> > > .
> > 
> > ## 
> > 
> > Doug Wendel
> > Professional Research Associate
> > University of Colorado at Boulder
> > Department of Chemistry and Biochemistry, Knight Lab
> > 303-641-5442
> > wendel@colorado.edu
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/382#issuecomment-17192862
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by ElDeveloper** [comment]
Looks great as well ... can we keep both? :P

Captura de pantalla 2013-04-29 a la s 14 50 40

Screenshot attached to see what others have to say.

**Comment by megalodonatron** [comment]
can you add a bit of margin to the right side of the twitter feed so that it matches up with the header? After that :shipit: :rabbit:

**Comment by douginator2000** [comment]
It's not just that, it varies because the header bar is percent width and
the twitter bar is anchored to the top right. Aside from the alignment
issues - do you think it's good/bad on the login page? Too busy? Better
place for it?

On Tuesday, April 30, 2013, Meg Pirrung wrote:

> can you add a bit of margin to the right side of the twitter feed so that
> it matches up with the header? After that [image: :shipit:][image:
> :rabbit:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/382#issuecomment-17247870
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
I think you should be able to add "float: right;" to the twitter thing and have it inside the content div and it should line up properly

**Comment by douginator2000** [comment]
For the moment I'm going to leave it off the login page - it looks very cluttered.

**Comment by ElDeveloper** [comment]
:+1:

**Pull request merged**
