### PR TITLE
Doug's First Pull Request!!!!!!!!!!!!!!!!!!!!!

### PR DESCRIPTION
**Pull request by douginator2000**
Just delete me.

### CODE REVIEW

**Comment by wasade** [comment]
im disappointed in the lack of 1s in the !!!!!. was expecting a little more
!!!111!1!!!1!!!!

**Comment by douginator2000** [comment]
Not merging.

**Comment by ElDeveloper** [comment]
@douginator2000 Remember you have to either delete the branch or remove your fork for this pull-request to disappear.

**Comment by douginator2000** [comment]
Okay I shall clear that out as well...

On Nov 9, 2012, at 3:02 PM, Yoshiki notifications@github.com wrote:

@douginator2000 https://github.com/douginator2000 Remember you have to
either delete the branch or remove your fork for this pull-request to
disappear.

—
Reply to this email directly or view it on
GitHubhttps://github.com/qiime/qiime_web_app/pull/61#issuecomment-10246221.

**Comment by douginator2000** [comment]
Umm... how do you delete a branch or fork from GitHub?

On Fri, Nov 9, 2012 at 3:29 PM, Doug Wendel douginator2000@gmail.comwrote:

> Okay I shall clear that out as well...
> 
> On Nov 9, 2012, at 3:02 PM, Yoshiki notifications@github.com wrote:
> 
> @douginator2000 https://github.com/douginator2000 Remember you have to
> either delete the branch or remove your fork for this pull-request to
> disappear.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/61#issuecomment-10246221.

## 

Doug Wendel, PRA
University of Colorado at Boulder
Department of Chemistry and Biochemistry
Knight Lab

**Comment by douginator2000** [comment]
Never mind... hehe

On Mon, Nov 12, 2012 at 9:29 AM, Doug Wendel douginator2000@gmail.comwrote:

> Umm... how do you delete a branch or fork from GitHub?
> 
> On Fri, Nov 9, 2012 at 3:29 PM, Doug Wendel douginator2000@gmail.comwrote:
> 
> > Okay I shall clear that out as well...
> > 
> > On Nov 9, 2012, at 3:02 PM, Yoshiki notifications@github.com wrote:
> > 
> > @douginator2000 https://github.com/douginator2000 Remember you have to
> > either delete the branch or remove your fork for this pull-request to
> > disappear.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/61#issuecomment-10246221.
> 
> ## 
> 
> Doug Wendel, PRA
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry
> Knight Lab

## 

Doug Wendel, PRA
University of Colorado at Boulder
Department of Chemistry and Biochemistry
Knight Lab

**Pull request closed without merging**
