### PR TITLE
Fix map markers on qiime and emp

### PR DESCRIPTION
**Pull request by teravest**
The map markers stopped working about a day ago but still worked on american gut.

I replaced the setMarkers function with the version of the function from the americangut page. 

Markers are displaying in firefox, Safari, and Chrome now.

### CODE REVIEW

**Comment by adamrp** [comment]
If it works, it works.. I just wish we knew _why_ it stopped working.  Do you think we can look into that a little bit before we merge?  It just seems weird to me that it would randomly stop working when we have changed nothing in our code... maybe the google maps API changed?

**Comment by ElDeveloper** [comment]
:+1:

**Comment by ElDeveloper** [comment]
@adamrp I'm going to bet right now that the problem is Google's API changing, from what @teravest mentioned in one of her e-mails.

**Comment by teravest** [comment]
This is on webdev now

**Comment by ElDeveloper** [comment]
Thanks for deploying this @teravest, just noticed that the markers are showing a "person" whilst these should be the generic Google Maps markers, aside from that, it looks great.

**Comment by adamrp** [comment]
Yep, the icons should be changed :+1:  Other than that, I'm happy with it!  Thanks, @teravest

**Comment by teravest** [comment]
Updated on webdev with no men

**Comment by ElDeveloper** [comment]
ginrhpd

**Pull request merged**
