### PR TITLE
some changes in barcode util

### PR DESCRIPTION
**Pull request by RNAer**
as requested by Mike. It allows wwwadmin users to specify more details about the sample in the emails sent out.

### CODE REVIEW

**Comment by mikewise** [comment]
I have interacted with several users in the help account after using the
scan utility as a means of contacting them. Adding barcode information is
not a problem once we've scanned the barcode, and there is no need to
change the ability to remove a barcode, once it's been scanned. This new
update increases the functionality of the tool to be more helpful when
contacting participants about adding their information on the Amgut user
interface.

**Comment by wasade** [comment]
Eta on production deployment?

**Comment by douginator2000** [comment]
Deployed. Please test and make sure it's working as expected.

**Comment by douginator2000** [comment]
Deployed - please test.

On Wed, Aug 7, 2013 at 10:19 AM, Daniel McDonald
notifications@github.comwrote:

> Eta on production deployment?
> 
> On Wednesday, August 7, 2013, mikewise wrote:
> 
> > I have interacted with several users in the help account after using the
> > scan utility as a means of contacting them. Adding barcode information
> > is
> > not a problem once we've scanned the barcode, and there is no need to
> > change the ability to remove a barcode, once it's been scanned. This new
> > update increases the functionality of the tool to be more helpful when
> > contacting participants about adding their information on the Amgut user
> > interface.
> > 
> > On Tue, Aug 6, 2013 at 2:39 PM, Zech Xu <notifications@github.com<javascript:_e({},
> > 'cvml', 'notifications@github.com');>>
> > wrote:
> > 
> > > as request by Mike. It allows wwwadmin users to specify more details
> > > about
> > > 
> > > ## the sample in the emails sent out.
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/RNAer/qiime_web_app tmp
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/qiime/qiime_web_app/pull/488
> > > Commit Summary
> > > - modified barcode_util
> > > - removed form_dict variable from barcode_util
> > > - layout changes
> > > 
> > > File Changes
> > > - _M_ www/wwwadmin/barcode_util.psp<
> > >   https://github.com/qiime/qiime_web_app/pull/488/files#diff-0>(138)
> > > 
> > > Patch Links:
> > > - https://github.com/qiime/qiime_web_app/pull/488.patch
> > > - https://github.com/qiime/qiime_web_app/pull/488.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/pull/488#issuecomment-22262096>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/488#issuecomment-22263473
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by mikewise** [comment]
Hopefully today...so I can flood the help account with emails.

**Comment by mikewise** [comment]
Thanks,

Will test now.

**Comment by wasade** [comment]
Thanks, will test in a second

**Comment by wasade** [comment]
Scan date on a few I spot checked show up as Aug 7 2013, but for the ones I
checked, I'm pretty sure that is not the case. Is that expected?

**Comment by RNAer** [comment]
that's because scan_date is null in the database (this was not used to
updated into database before I changed barcode util). the util currently
works like this:

if it doesn't get scan_date from database, it assume it's the 1st time the
barcode is scanned, thus showing the current date and updating it to the
database by submitting the form; otherwise, showing the scan_date in the
database.

**Comment by wasade** [comment]
Okay. We may want the default behavior to indicate that the return date is
unknown. I'm nervous about knowingly injecting false data into the db

**Comment by RNAer** [comment]
I thought this is specifically designed for barcode scanning instead of
barcode editing (we already has another psp page to do that, or probably we
should merge these 2). that being said, it can be changed to alternatives:
1. provide a text box and let users to input the date. Mike is gonna to
   click/type more
2. is there other way to tell whether this is the first time we meet the
   barcode? scan_date is the only one I could find to do that

**Comment by mikewise** [comment]
Doesn't the submit button add to the database? Not simply the act of
scanning? I guess if I have backlog to do, then it will say that they are
received today. maybe we should make a distinction between the scan date
and the received date?

**Comment by wasade** [comment]
ah, okay, scan date makes more sense now. we definitely want to track receive date, and i just wanted to make sure that we don't inject false data there.

**Comment by mikewise** [comment]
I agree, since I have about 100 samples backlogged, only thing I can say is
that as soon as I have the emails sent out from those 100 samples, I can
give doug the spreadsheet that has the actual received date, and he can
push those to the database as the most up to date values.

**Pull request merged**
