### PR TITLE
Only pull down Month and Year

### PR DESCRIPTION
**Pull request by adamrp**
We should change the web interface as well, but in the meantime this will suffice to pull down only the month and year of the birthdate provided by participants.  EBI still needs to be updated.

### CODE REVIEW

**Comment by teravest** [comment]
looks good to me!

**Comment by teravest** [comment]
This doesn't seem to be working when I translated it to postgres

**Comment by adamrp** [comment]
Hmm, the syntax looks the same... I'll do some testing.

**Comment by adamrp** [comment]
The `replace` function is slightly different in postgres, as it requires the third parameter (whereas it is optional in Oracle).  Also, the `regexp_replace` function needs a few extra backslashes, and an 'E' prefix in postgres:

``` postgres
regexp_replace(replace(replace(replace(birth_date, CHR(10), ''), CHR(13), ''), CHR(9), ''), '([[:digit:]]{2})/([[:digit:]]{2})/([[:digit:]]{4})', E'\\1/\\3');
```

**Comment by teravest** [comment]
thanks!   it works now

**Pull request merged**
