### PR TITLE
reassigned barcodes to ICU microbiome project

### PR DESCRIPTION
**Pull request by wasade**
barcodes reassigned to University of Colorado ICUs

### CODE REVIEW

**Comment by wasade** [comment]
Do not merge yet, coordinating with @douginator2000 on how we want to proceed with these barcodes

**Comment by douginator2000** [comment]
Max ID at the moment is 000005971. You're probably fine with the range you
selected - was there a reason you started at 6136? At some point we'll need
to discuss a centralized barcode strategy.

On Wed, Jun 5, 2013 at 3:10 PM, Daniel McDonald notifications@github.comwrote:

> Do not merge yet, coordinating with @douginator2000https://github.com/douginator2000on how we want to proceed with these barcodes
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/421#issuecomment-19008812
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by wasade** [comment]
6135 was the last printed barcode, and I need to reprint these as there I'm annotating them. I definitely agree we should look at centralizing barcodes but I'm not sure right now what that would entail.

I'm nervous about using 6136 - 6616 though since we haven't centralized barcodes. We will be generating probably a few more thousand for american gut, so we'll already be overlapping that range.  

To avoid doing something really hackish now that we'll hate ourselves for later, I'm creating new barcodes well out of range for this project. This pull request should not be merged and should be closed.

**Comment by douginator2000** [comment]
If the new barcodes go in the handout table then we should avoid most of
these issues.

On Wed, Jun 5, 2013 at 3:42 PM, Daniel McDonald notifications@github.comwrote:

> 6135 was the last printed barcode, and I need to reprint these as there
> I'm annotating them. I definitely agree we should look at centralizing
> barcodes but I'm not sure right now what that would entail.
> 
> I'm nervous about using 6136 - 6616 though since we haven't centralized
> barcodes. We will be generating probably a few more thousand for american
> gut, so we'll already be overlapping that range.
> 
> To avoid doing something really hackish now that we'll hate ourselves for
> later, I'm creating new barcodes well out of range for this project. This
> pull request should not be merged and should be closed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/421#issuecomment-19010797
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by wasade** [comment]
On further discussion with @douginator2000 it sounds like using these barcodes is the best way forward. Safe to merge...

**Comment by adamrp** [comment]
Still safe to merge this?  I assume so, but the "safe to merge" comment is a month old at this point.

**Comment by douginator2000** [comment]
Should be?

On Mon, Jul 1, 2013 at 1:28 PM, adamrp notifications@github.com wrote:

> Still safe to merge this? I assume so, but the "safe to merge" comment is
> a month old at this point.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/421#issuecomment-20304432
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Pull request merged**
