### PR TITLE
Add Rob Dunn's Amgut 101 text to FAQ and top-level menu

### LINKED ISSUE #497: Update FAQ site
@mikewise pointed out that with the recent changes to the GUI, some sections of the FAQ page are now outdated.

### PR DESCRIPTION
**Pull request by adamrp**
Please review and merge ASAP, need to get link to Rob so he can send out request for additional collaborators to contribute to the project.  @wasade, can you review the text and formatting please?  After that, can you please merge, Doug?  @meganap also contributed new FAQ images to this pull request so that it fixes #497.

### CODE REVIEW

**Comment by douginator2000** [comment]
Sure can do. This is all on webdev?

**Comment by adamrp** [comment]
it is now -- @RNAer, your branch was checked out on webdev, so I just merged this into your dev branch.  Shouldn't be a problem I think...

**Comment by wasade** [comment]
Will review in 2hrs

**Comment by adamrp** [comment]
Thank you!

**Comment by wasade** [comment]
where is it located?

**Comment by wasade** [comment]
text and formatting looks good, but can we make it more prominent? I think this should be its own link, not under FAQ

**Comment by adamrp** [comment]
Weird, it was also on the menu when I last looked but that's gone now! I'll re-add it to the side menu, right under "Home"

**Comment by adamrp** [comment]
The code was actually still there, but for some reason it was not displaying properly until apache was restarted, so it's now on the main menu.

**Comment by wasade** [comment]
thanks. only other suggestion would be to add an American Gut 101 link on the login page as well so that people can access the text without having to be a participant

**Comment by wasade** [comment]
rather, they don't have be logged in, but it is easy to access if they aren't logged in

**Comment by adamrp** [comment]
gotcha, can do

**Comment by adamrp** [comment]
If there are no other comments, I believe this is ready to merge and deploy

**Pull request merged**
