### PR TITLE
Add Tito Jankowski's how-to in survey info

### PR DESCRIPTION
**Pull request by ElDeveloper**
Linking to Tito's How-To guide in the survey information that we have in
the step by step guide.

@wasade, once this is merged, I'll contact Tito as you initially requested.

### CODE REVIEW

**Comment by wasade** [comment]
any reason to this shouldn't be merged?

**Comment by ElDeveloper** [comment]
Not that I can think of.

Yoshiki.

**Comment by wasade** [comment]
@adamrp interested in doing another push live sometime?

**Comment by adamrp** [comment]
Sure thing. Tomorrow AM?

**Comment by ElDeveloper** [comment]
Thanks!

**Comment by wasade** [comment]
Excellent, thanks

**Pull request merged**
