### PR TITLE
removed all references to StyledMarker.js in the codebase

### PR DESCRIPTION
**Pull request by teravest**
Map markers were not showing up in the georeferencing code either.

### CODE REVIEW

**Comment by teravest** [comment]
This is deployed on webdev now

**Comment by adamrp** [comment]
Awesome, thanks @teravest!  Just curious, I see that in some files just one line was removed where it loaded the StyledMarker.js file; is StyledMarker really just not used in those files?

**Comment by adamrp** [comment]
looks good to merge imo :+1:

**Comment by teravest** [comment]
StyleMarker.js was used in ontology.js which is the next include below.
 Instead of having ontology.js include StyleMarker.js you had to include it
before including ontology.js

**Comment by ElDeveloper** [comment]
Looks good, tested it out and everything seems to be working just fine.

**Comment by adamrp** [comment]
Ahh, I see.  Thanks!  Okay, merging.

**Comment by ElDeveloper** [comment]
:+1:

**Comment by rob-knight** [comment]
I can confirm that it’s working on the live site (just in time for graduating recruiting today) — thanks so much!

Rob

On Mar 7, 2014, at 1:47 PM, Yoshiki Vázquez Baeza <notifications@github.com<mailto:notifications@github.com>> wrote:

[https://github.global.ssl.fastly.net/images/icons/emoji/%2B1.png]

**Pull request merged**
