### PR TITLE
Menu redesign

### PR DESCRIPTION
**Pull request by megalodonatron**
The old menu was getting pretty ugly so I redesigned it so that it is hierarchical and opens on hovering. I've attached a screenshot of what it looks like now.

screen shot 2013-08-09 at 3 36 18 pm

### CODE REVIEW

**Comment by douginator2000** [comment]
Meg, looks promising. Can you deploy it on webdev so we can all test it out?

On Fri, Aug 9, 2013 at 3:41 PM, Meg Pirrung notifications@github.comwrote:

> The old menu was getting pretty ugly so I redesigned it so that it is
> hierarchical and opens on hovering. I've attached a screenshot of what it
> looks like now.
> 
> ## [image: screen shot 2013-08-09 at 3 36 18 pm]https://f.cloud.github.com/assets/930642/941091/60db2bda-013c-11e3-87dc-1c0a0dcff966.png
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/meganap/qiime_web_app menu_redesign
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/qiime/qiime_web_app/pull/493
> Commit Summary
> - Merge pull request #2 from meganap/portal_redesign
> - Merge branch 'master' of github.com:meganap/qiime_web_app
> - Merge branch 'master' of https://github.com/qiime/qiime_web_app
> - Checking in menu redesign
> 
> File Changes
> - _M_ www/americangut/header.psphttps://github.com/qiime/qiime_web_app/pull/493/files#diff-0(1)
> - _M_ www/americangut/log_portal.psphttps://github.com/qiime/qiime_web_app/pull/493/files#diff-1(8)
> - _M_ www/americangut/menu.psphttps://github.com/qiime/qiime_web_app/pull/493/files#diff-2(168)
> - _M_ www/americangut/style/americangut.csshttps://github.com/qiime/qiime_web_app/pull/493/files#diff-3(3)
> - _A_ www/americangut/style/menu.csshttps://github.com/qiime/qiime_web_app/pull/493/files#diff-4(138)
> 
> Patch Links:
> - https://github.com/qiime/qiime_web_app/pull/493.patch
> - https://github.com/qiime/qiime_web_app/pull/493.diff

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by megalodonatron** [comment]
Will do! :rabbit:

**Comment by wasade** [comment]
Any progress on the taxonomy work or the module 1 draft? That work is
prioritized over UI modifications, and do not want to pull off developer
hours testing this until higher priority tasks are completed.

**Comment by megalodonatron** [comment]
Yeah I'm working on it, I just got stuck at a point and so needed to work on something else for a bit.

**Comment by wasade** [comment]
Okay, thanks

**Comment by adamrp** [comment]
This looks great!  I noticed a couple things.  I think the "Add Human Source" (or animal source, or log sample) links should be a different color, or maybe a different style (e.g., bold/italic?)  I also notice that the cursor changes to a hand for some of the links but not others (e.g., it does not change to a hand when hovering over participant names or the "Log Sample" links -- this is a minor thing, obviously).

**Comment by megalodonatron** [comment]
Thanks Adam, I've deployed those changes.

**Comment by RNAer** [comment]
+1

**Pull request merged**
