### PR TITLE
Fix for issue 503, participants now can not do anything unless they verify

### PR DESCRIPTION
**Pull request by megalodonatron**
Fixes issue #503

### CODE REVIEW

**Comment by ElDeveloper** [comment]
This looks all good to me. Tested it on my local virtual box and everything is displaying correctly, what I did for my test:
- Reset the verification code for the test account.
- Log in to the website.
- Check that I could not do anything else but verifying my kit.
- Verify the kit.
- Check that I could interact with the system without a problem.

**Comment by ElDeveloper** [comment]
A ping to @adamrp, @wasade, @RNAer or @teravest, if this looks good to any of you, please :+1: it and we should merge it.

**Comment by adamrp** [comment]
Even before verifying, I am able to add a human source.  Is there any way to disable interacting with the menu?  I can't think of an easy way to prevent that, though, since fusebox loads header (which loads menu) before it loads portal... unless we set the kit_verified boolean in header.

**Comment by adamrp** [comment]
Also, I can now return to the verification tab after verifying; this did not used to be the case.  Can we disable the verification tab if the kit is already verified?

**Comment by megalodonatron** [comment]
I added logic around the "add human source" that shouldn't write it to the page unless the kit is already verified. I can add logic to disable the verification tab once the kit has been verified.

**Comment by adamrp** [comment]
That would be awesome, thanks, Meg.  The logic that is supposed to prevent writing Add Human Source to the page does not seem to be working, unless I'm doing something wrong (this branch is currently deployed on webdev, check it out)

**Comment by megalodonatron** [comment]
Added logic so that once the kit is verified that tab is greyed out and can't be selected. Everything should be good to go now.

**Comment by adamrp** [comment]
:+1: going to merge this in 15 mins unless i hear an objection

**Pull request merged**
