### PR TITLE
Add flush of output buffers for logging

### PR DESCRIPTION
**Pull request by adamrp**
This modification should ensure that logs are completely written, and not left in an incomplete state with things left in the write buffer, if the job crashes or has to be killed.

### CODE REVIEW

**Comment by wasade** [comment]
Is good to merge, can't from phone (login issues ATM)

This is one reason we shouldn't reinvent these services, particularly when
they're already available from python natively. Thanks for tracking this
down

**Comment by wasade** [comment]
Hah, beat me to it... :)

**Comment by adamrp** [comment]
Hah thanks guys :) just deployed on www

**Comment by ElDeveloper** [comment]
Haha, no problem.

Just in case: GitHub's mobile interface will not show you the full diff but will let you merge the branch. I had to switch from mobile version to desktop version to review the code and then back to merge the branch.

**Pull request merged**
