### PR TITLE
Modify editing of human surveys

### LINKED ISSUE #524: wwwadmin site cannot be used to update participant name
The SQL statement is like this:

update ag_human_survey set participant_name = '<new name>' where ag_login_id = 'xxxx' and participant_name = '<new_name>'

(See ag_data_access.updateAGSurvey)

This won't work because there is no participant with <new_name> for that login_id (presumably), so no rows are updated. This can be fixed by special casing the form input for participant name.

### PR DESCRIPTION
**Pull request by adamrp**
Previously, the participant's name could not be updated on wwwadmin (it would
fail silently). Had to make a special case for this field.

This fixes #524

### CODE REVIEW

**Comment by adamrp** [comment]
To test this, use virtual box. Edit a human survey, and see if the participant's name actually changes.  Note that any samples associated with the OLD name are NOT updated automatically!!  This should be added before merge.

**Comment by ElDeveloper** [comment]
So this is not ready for merge?

**Comment by adamrp** [comment]
I wouldn't merge it yet, although the code does work for fixing the ineffective participant_name update code. The problem is that any samples associated with the participant will not be updated to be associated with the new participant.

**Comment by ElDeveloper** [comment]
Gotcha, thanks!

**Comment by adamrp** [comment]
I only realized this after the fact, which is why i prematurely submitted the pull request :)

**Comment by adamrp** [comment]
This should be good to go now, but someone should test, ideally.

**Comment by teravest** [comment]
:+1:

**Pull request merged**
