### PR TITLE
Checking in generic add sample landing page

### PR DESCRIPTION
**Pull request by megalodonatron**
Fixes issue #568

Adds a top level menu item to "Log Sample..."
This option is only available after the kit has been verified.
Lists all available sources to choose from and will take the user to the intended add sample page when clicked.

screen shot 2014-01-07 at 7 53 32 pm

I also updated the add_animal_sample page so that it lists the name of the clicked animal at the top as it does on the add human sample page.

### CODE REVIEW

**Comment by megalodonatron** [comment]
This pull req is ready to be deployed and tested on webdev.

**Comment by megalodonatron** [comment]
This is currently deployed on webdev for testing

**Comment by adamrp** [comment]
This looks pretty good, thanks @meganap!  One thing I noticed is that if the participant has unassigned barcodes, the "Log Sample" link is still present when you go through the menu hierarchies (hover over Human Samples -> Hover over name -> select "Log Sample") -- do we want the link to appear in both places?

Also, if there are NOT unassigned barcodes, the top-level "Log Sample" link (the new one that you just added) still appears.  Clicking that link bring sup the add_sample page, but there is no barcode available in the dropdown.  Hitting submit gives you a traceback.

**Comment by megalodonatron** [comment]
Yeah I was wondering when I was doing this whether or not we should keep the "log sample" links in the menus when we have the main level one. I would vote to remove them from the inner menus.

I will add logic to not show the "log sample" link if there are no unassigned barcodes.

**Comment by adamrp** [comment]
My inclination is to remove them, keeping _only_ the top-level link, but
I'd be interested to hear others' opinions.

**Comment by megalodonatron** [comment]
Made updates and redeployed on webdev

**Comment by adamrp** [comment]
This looks good to me and works, as far as I can tell.  Does anyone else want to test, or shall I merge?

**Comment by adamrp** [comment]
No responses, so I'm merging now

**Pull request merged**
