### PR TITLE
gzipped SFF files will now work

### PR DESCRIPTION
**Pull request by adamrp**
unless they are in the "special cases" list in run_process_sff_through_split_lib.py.

### CODE REVIEW

**Comment by adamrp** [comment]
Oops -- Hold off on merging this until I edit test code.

**Comment by douginator2000** [comment]
Will do. Also, are you confident that this will work in general cases
beyond your test dataset? I.e. if I deploy this to the live server, are you
confident it will just work?

On Mon, Feb 4, 2013 at 3:36 PM, adamrp notifications@github.com wrote:

> Oops -- Hold off on merging this until I edit test code.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/120#issuecomment-13103900.

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by adamrp** [comment]
The test code and support file are ready and committed here, so the pull request should be ready to merge.  I'm confident that it will work.  If you want to run additional tests, you can always checkout the branch on webdev.  The test code all passes, and I tried two test studies (1698 and 1699, gzip_sff_test and gzip_sff_titanium_test), both of which work.  The only time it fails, as I noted, is when: 1) the study is in the "special cases" list, and 2) the SFF file is gzipped.  In that case, it fails and says "please unzip the SFF"

**Comment by douginator2000** [comment]
Awesome, sounds good Adam and thanks - I'll trust your testing and deploy
it tomorrow.

On Mon, Feb 4, 2013 at 4:47 PM, adamrp notifications@github.com wrote:

> The test code and support file are ready and committed here, so the pull
> request should be ready to merge. I'm confident that it will work. If you
> want to run additional tests, you can always checkout the branch on webdev.
> The test code all passes, and I tried two test studies (1698 and 1699,
> gzip_sff_test and gzip_sff_titanium_test), both of which work. The only
> time it fails, as I noted, is when: 1) the study is in the "special cases"
> list, and 2) the SFF file is gzipped. In that case, it fails and says
> "please unzip the SFF"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/120#issuecomment-13106875.

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by douginator2000** [comment]
Merged request and ran a study - fails on live. Adam will you look into this ASAP?

**Pull request merged**
