### PR TITLE
Fix imports in live_ebi_sra_rest_services

### LINKED ISSUE #683: EBI submission is currently broken
The imports in live_ebi_sra_rest_services.py ([Lines 12-21](https://github.com/qiime/qiime_web_app/blob/master/python_code/live_ebi_sra_rest_services.py#L12-L21)) need to be cleaned up; the biggest problem is line 12, where `environ` is imported from `os.path` when in fact it is in `os`.

### PR DESCRIPTION
**Pull request by adamrp**
environ was coming from the wrong place, and there were a couple unused
imports. Fixes #683

### CODE REVIEW

**Comment by adamrp** [comment]
Because I had to submit something to EBI tonight, I already made these changes on live.  If it works, we should merge this and deploy; I'll update when the submission completes/terminates.

**Comment by adamrp** [comment]
The submission was successful, so this should be merged and deployed following review

**Comment by teravest** [comment]
:+1: @ElDeveloper   I am ok with merging this.

**Comment by ElDeveloper** [comment]
That was my bad @adamrp, thanks for fixing it :+1:

**Comment by adamrp** [comment]
No problem!  Thanks for the prompt attention.  It was all of our mistake -- you wrote it, but we both reviewed it :cry: and apparently none of us tested it.  That's bad!  At least it was an easy fix, but we should all be better than that.

**Comment by ElDeveloper** [comment]
I thought I tested it, but what I probably tested was probably the 'dirty' solution on live and that definitely was different from my PR.

**Pull request merged**
