### PR TITLE
Add water as environmental sample type

### LINKED ISSUE #677: Add "water" environmental sample type
Jeff wanted to take a water sample, but this sample type is not currently available.

### PR DESCRIPTION
**Pull request by adamrp**
Fixes #677

This turned out to be very easy :)

### CODE REVIEW

**Comment by ElDeveloper** [comment]
:+1:

**Comment by teravest** [comment]
:+1:

**Comment by adamrp** [comment]
Someone want to merge?  Would like to deploy this soon since Jeff Leach
needs to log some water samples he took.

**Comment by ElDeveloper** [comment]
t0klc0c

**Pull request merged**
