### PR TITLE
Add format template to date and hour in add sample

### PR DESCRIPTION
**Pull request by ElDeveloper**
Add `mm/dd/yyyy` to the side of each of the date text entry boxes in the
three `add_sample_*.psp` menus, as well as `hh:mm AM/PM` for the collection
hour.

Note that I selected `hh:mm AM/PM` instead of `hh:mm tt` because I figured it wouldn't be clear for some people.

### CODE REVIEW

**Comment by douginator2000** [comment]
Looks good, though it might be even more helpful for the challenged to include an actual example, like "Example: 05/07/2013" and "Example: 04:35 PM"

**Comment by ElDeveloper** [comment]
Sounds good, should be in place now.

Should the format examples in the questionnaire be updated as well
following this same suggestions?

2013/5/8 Doug Wendel notifications@github.com

**Comment by megalodonatron** [comment]
:shipit: :rabbit:

**Comment by megalodonatron** [comment]
I think the example format with just mm/dd/yyyy is pretty understandable

**Comment by ElDeveloper** [comment]
Sounds good :+1:

**Pull request merged**
