### PR TITLE
Add enforcement of sample site selection

### PR DESCRIPTION
**Pull request by adamrp**

### CODE REVIEW

**Comment by adamrp** [comment]
Forgot to mention it in a commit message, but this will fix #490

**Comment by wasade** [comment]
not sure if pertinent on this pull request, but it is possible to enter invalid times
screen shot 2013-08-13 at 4 06 08 pm

**Comment by adamrp** [comment]
At least for the date, you can enter it, but it will not let you submit the form.  The time validation, on the other hand, does indeed not seem to be working.  I'll submit another commit shortly....

**Comment by adamrp** [comment]
fixed time validation and deployed on webdev.

**Pull request merged**
