### PR TITLE
Added sample sites for office succession

### PR DESCRIPTION
**Pull request by wasade**
Added sample types for the office succession project

@gregcaporaso I think this covers what is necessary and was much lighter changes than anticipated. Once live, should just be on the forms when adding samples.

@douginator2000 I couldn't drop this in the dev environment due to the current qb downtime, but the changes are very minimal.

### CODE REVIEW

**Comment by douginator2000** [comment]
So this changes the possible human sampling sites - Has anyone chatted with Gail RE IRB concerns here? I know the original list was chosen and stuck to because that's how it was written in the IRB docs.

**Comment by rob-knight** [comment]
Yes

On Jun 14, 2013, at 12:56 PM, "Doug Wendel" <notifications@github.com<mailto:notifications@github.com>> wrote:

So this changes the possible human sampling sites - Has anyone chatted with Gail RE IRB concerns here? I know the original list was chosen and stuck to because that's how it was written in the IRB docs.

**Comment by gregcaporaso** [comment]
Thanks!

**Comment by wasade** [comment]
@douginator2000 this needs to be merged live ASAP

**Pull request merged**
