### PR TITLE
change email message when sample not logged

### LINKED ISSUE #695: Change email about missing sample info.
Elaine suggested 
Dear _______,

We have recently received your sample barcode: ________, but we cannot process your sample until the following steps have been completed online. Please ensure that you have completed both steps outlined below:

1). Submit consent form & survey
For human samples, the consent form is mandatory. Please note that the consent form is located on the first page of the survey. Even if you elect not to answer the questions on the survey (as every question is optional), please click through and submit the survey in order to ensure we receive your completed consent form. 
For pet samples, we ask that you fill out a short survey. No consent form is necessary
For environmental samples, no consent form or survey is necessary. Please skip to step 2 below.
2). Log your sample
_Note that for human & pet samples, the survey must be completed before doing this step_ 

In order to log your sample, please log into your account and click the "Log Sample" button at the bottom of the left-hand navigation menu. This will bring you to a screen with the heading "Choose your sample source". Click on the name that the sample belongs to, then fill out the prompted fields. To facilitate this process, the details you included on the side of your sample tube are:
Sample Date: _________
Sample Time: _________

Our website is located at www.microbio.me/americangut. If you have any questions, please contact us at info@americangut.org.

Thank you,
American Gut Team

Current wording is 
Dear {name},

We have recently received your sample barcode: {barcode}, but we cannot process your sample until the online forms have been completed.  Information about your sample is tracked through the American Gut participant website, and you are required to log in and complete the online process in order for your sample to be processed. 

If it is a human sample, we require formal consent, questionnaire results and sample details (type, date, and time of collection). If it is a pet or environmental sample we require sample details (type, date and time of collection). If you have already filled out the consent form and questionnaire, then it is likely that the sample simply needs to be associated with the appropriate participant.

In order to help you in adding these details, the side of the sample tube {barcode} reads:
   sample date: {sample_date} 
   sample time: {sample_time}

Instructions about the required procedures can be found here: http://www.microbio.me/americangut/img/full_instructions.pdf

These procedures are in place to protect your privacy, and please be sure that we are properly associating your sample to your survey results. We realize that some of these steps may not be completely intuitive. However, our kits are designed to support multiple participants and sample types, which necessitates the added complexity of explicitly requiring participants to associate samples with themselves so that we can guarantee compliance with human subjects research protocols.

Please log back into the American Gut website (http://www.microbio.me/americangut) as soon as possible and complete the online process. If you have any questions or concerns, please contact us at info@americangut.org.

Thank you,

--American Gut Team--

@ackermag 
Do we have any IRB issues here.  I don't think we do, but I wanted to double check.

### PR DESCRIPTION
**Pull request by teravest**
fixes#695

We need to test this on webdev before merging. And we need Gail to verify IRB concerns.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
The message looks ok to me :+1:

**Comment by teravest** [comment]
it is on webdev now

**Comment by adamrp** [comment]
Can we merge this?  Did @ackermag comment on whether or not a change to this text requires input from the IRB?  I think it doesn't, but @rob-knight wanted to double check.

**Comment by ElDeveloper** [comment]
Let's wait until we hear confirmation about this.

**Comment by adamrp** [comment]
@ackermag, we are just looking a `yes` or `no` on this one: does a change to this email require IRB approval?

This is the email that is sent out to participants when we receive a sample that has not been logged. As far as I know, it does not, but we needed confirmation before we can deploy this change.

**Comment by teravest** [comment]
@ackermag Hey Gail,  we are still waiting for a response from you to know if this email change requires IRB approval or if we can merge and deploy.

**Comment by ackermag** [comment]
Sorry Emily
I now realize I didn't tell you just Daniel - it does not require IRB
approval.

On Wed, May 14, 2014 at 10:43 AM, teravest notifications@github.com wrote:

> @ackermag https://github.com/ackermag Hey Gail, we are still waiting
> for a response from you to know if this email change requires IRB approval
> or if we can merge and deploy.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/696#issuecomment-43105730
> .

## 

Gail Ackermann
Knight Lab UCB 596
University of Colorado
Boulder

**Comment by teravest** [comment]
Thanks @ackermag  we should be able to get this deployed tomorrow

**Comment by ElDeveloper** [comment]
So merging then?

**Comment by teravest** [comment]
please

**Pull request merged**
