### PR TITLE
Add kit id and kit email to email about child participant

### PR DESCRIPTION
**Pull request by teravest**
3 things changed here. 

The bullet point for "juvenile_age_less_than_7" now reads "Participant is older than 3 months and younger than 7 years of age" instead of "Participant is older than 3 months and younger than 13 years of age"

two new pieces of information are added to the email that gets sent to the help account. 
kit_id and
kit email address

Previously only the ag_login_id was provided and I would have to look up the kit id for Elaine based on the ag_login_id

### CODE REVIEW

**Comment by ElDeveloper** [comment]
This looks good :+1:, should we test after we figure out what we want to do to test #607 ?

**Comment by teravest** [comment]
can we get this one in on the deploy too?  I completely forgot about this one, but it would make Elaine and Dana's lives a lot easier.

**Comment by ElDeveloper** [comment]
Yes, I remember testing this and remembering everything was ok.

**Comment by ElDeveloper** [comment]
@adamrp want to take a look?

**Comment by teravest** [comment]
I'll toss it up on webdev

**Comment by adamrp** [comment]
Thanks, I remember this being fine, too -- please merge away!

**Comment by ElDeveloper** [comment]
Thanks @teravest

**Pull request merged**
