### PR TITLE
added make samples script

### PR DESCRIPTION
**Pull request by wasade**
This takes is from the phase info we get from Jeff to having samples, kit ids, verification codes, passwords, etc. DB checks are in place on kit ids and sample ids. This does not create barcodes as that is not an entirely reliable operation yet and requires some manual intervention. I can of course add tests in on this stuff, let me know if necessary.

### CODE REVIEW

**Comment by wasade** [comment]
Going to add a few more components to this, so don't merge yet. Specifically, automatically print out the kit ID sheets, I'll figure out something for the barcodes.

**Comment by megalodonatron** [comment]
Should also update according to issue #300

**Comment by douginator2000** [comment]
Is this ready for merge or not yet complete?

**Comment by wasade** [comment]
@douginator2000 still pending. Am aiming get this out today

**Comment by wasade** [comment]
afaik only thing missing out of here is generation of barcodes, which @douginator2000 and I discussed last week about just doing in bulk and separate.

**Pull request merged**
