### PR TITLE
barcode util changed

### PR DESCRIPTION
**Pull request by RNAer**
reduced the number of email types two 2; cleaned ag_check_barcode_status.sql.

please deploy the ag_check_barcode_status.sql to beast.

### CODE REVIEW

**Comment by douginator2000** [comment]
Testable on webdev?

**Comment by RNAer** [comment]
both of my pull requests are on webdev right now for test

**Comment by douginator2000** [comment]
Is this good to go? Everyone is satisfied it won't break stuff? :D

**Comment by RNAer** [comment]
yup

**Comment by douginator2000** [comment]
All deployed on live - can you verify that it's working as expected?

On Wed, Sep 4, 2013 at 2:11 PM, Zech Xu notifications@github.com wrote:

> yup
> 
> On Wed, Sep 4, 2013 at 11:51 AM, Doug Wendel notifications@github.comwrote:
> 
> > Is this good to go? Everyone is satisfied it won't break stuff? :D
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23809688>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/498#issuecomment-23820148
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by RNAer** [comment]
it seems alright to me. thanks.

**Comment by rob-knight** [comment]
The web site is not working for me for meta-analysis right now (tried both PCoA and taxonomy on different datasets; problem is that jobs don't show up in the usual list, so not even the OTU table builds). Problem started about 10 min ago when I got a "list index out of range" traceback when trying to look at the PGP fecal data.

On Sep 6, 2013, at 12:10 PM, Doug Wendel <notifications@github.com<mailto:notifications@github.com>> wrote:

All deployed on live - can you verify that it's working as expected?

On Wed, Sep 4, 2013 at 2:11 PM, Zech Xu <notifications@github.com<mailto:notifications@github.com>> wrote:

> yup
> 
> On Wed, Sep 4, 2013 at 11:51 AM, Doug Wendel <notifications@github.com<mailto:notifications@github.com>>wrote:
> 
> > Is this good to go? Everyone is satisfied it won't break stuff? :D
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23809688>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/498#issuecomment-23820148
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edumailto:wendel@colorado.edu

**Comment by douginator2000** [comment]
Checking. Which studies were you working with?

On Fri, Sep 6, 2013 at 12:16 PM, Rob Knight notifications@github.comwrote:

> The web site is not working for me for meta-analysis right now (tried both
> PCoA and taxonomy on different datasets; problem is that jobs don't show up
> in the usual list, so not even the OTU table builds). Problem started about
> 10 min ago when I got a "list index out of range" traceback when trying to
> look at the PGP fecal data.
> 
> On Sep 6, 2013, at 12:10 PM, Doug Wendel <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> All deployed on live - can you verify that it's working as expected?
> 
> On Wed, Sep 4, 2013 at 2:11 PM, Zech Xu <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> > yup
> > 
> > On Wed, Sep 4, 2013 at 11:51 AM, Doug Wendel <notifications@github.com
> > <mailto:notifications@github.com>>wrote:
> > 
> > > Is this good to go? Everyone is satisfied it won't break stuff? :D
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23809688>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23820148>
> > .
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edumailto:wendel@colorado.edu
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23958732>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/498#issuecomment-23959151
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by douginator2000** [comment]
I can verify that Bobe_PGP fails. Any others?

On Fri, Sep 6, 2013 at 12:20 PM, Doug Wendel douginator2000@gmail.comwrote:

> Checking. Which studies were you working with?
> 
> On Fri, Sep 6, 2013 at 12:16 PM, Rob Knight notifications@github.comwrote:
> 
> > The web site is not working for me for meta-analysis right now (tried
> > both PCoA and taxonomy on different datasets; problem is that jobs don't
> > show up in the usual list, so not even the OTU table builds). Problem
> > started about 10 min ago when I got a "list index out of range" traceback
> > when trying to look at the PGP fecal data.
> > 
> > On Sep 6, 2013, at 12:10 PM, Doug Wendel <notifications@github.com
> > <mailto:notifications@github.com>> wrote:
> > 
> > All deployed on live - can you verify that it's working as expected?
> > 
> > On Wed, Sep 4, 2013 at 2:11 PM, Zech Xu <notifications@github.com<mailto:
> > notifications@github.com>> wrote:
> > 
> > > yup
> > > 
> > > On Wed, Sep 4, 2013 at 11:51 AM, Doug Wendel <notifications@github.com
> > > <mailto:notifications@github.com>>wrote:
> > > 
> > > > Is this good to go? Everyone is satisfied it won't break stuff? :D
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23809688>
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23820148>
> > > .
> > 
> > ## 
> > 
> > Doug Wendel
> > Professional Research Associate
> > University of Colorado at Boulder
> > Department of Chemistry and Biochemistry, Knight Lab
> > 303-641-5442
> > wendel@colorado.edumailto:wendel@colorado.edu
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23958732>.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/498#issuecomment-23959151
> > .
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edu

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by douginator2000** [comment]
It appears to be related to the ethnicity field. If you select all but that
it generates a mapping file. Checking what the issue might be with that
field now.

On Fri, Sep 6, 2013 at 12:20 PM, Doug Wendel douginator2000@gmail.comwrote:

> I can verify that Bobe_PGP fails. Any others?
> 
> On Fri, Sep 6, 2013 at 12:20 PM, Doug Wendel douginator2000@gmail.comwrote:
> 
> > Checking. Which studies were you working with?
> > 
> > On Fri, Sep 6, 2013 at 12:16 PM, Rob Knight notifications@github.comwrote:
> > 
> > > The web site is not working for me for meta-analysis right now (tried
> > > both PCoA and taxonomy on different datasets; problem is that jobs don't
> > > show up in the usual list, so not even the OTU table builds). Problem
> > > started about 10 min ago when I got a "list index out of range" traceback
> > > when trying to look at the PGP fecal data.
> > > 
> > > On Sep 6, 2013, at 12:10 PM, Doug Wendel <notifications@github.com
> > > <mailto:notifications@github.com>> wrote:
> > > 
> > > All deployed on live - can you verify that it's working as expected?
> > > 
> > > On Wed, Sep 4, 2013 at 2:11 PM, Zech Xu <notifications@github.com
> > > <mailto:notifications@github.com>> wrote:
> > > 
> > > > yup
> > > > 
> > > > On Wed, Sep 4, 2013 at 11:51 AM, Doug Wendel <notifications@github.com
> > > > <mailto:notifications@github.com>>wrote:
> > > > 
> > > > > Is this good to go? Everyone is satisfied it won't break stuff? :D
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23809688>
> > > > > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23820148>
> > > > .
> > > 
> > > ## 
> > > 
> > > Doug Wendel
> > > Professional Research Associate
> > > University of Colorado at Boulder
> > > Department of Chemistry and Biochemistry, Knight Lab
> > > 303-641-5442
> > > wendel@colorado.edumailto:wendel@colorado.edu
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23958732>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/498#issuecomment-23959151
> > > .
> > 
> > ## 
> > 
> > Doug Wendel
> > Professional Research Associate
> > University of Colorado at Boulder
> > Department of Chemistry and Biochemistry, Knight Lab
> > 303-641-5442
> > wendel@colorado.edu
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edu

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by douginator2000** [comment]
Two issues appear to exist. One: There was some data in the ethnicity field
which contained invalid characters (i.e. line break) - probably a
copy/paste issue in the metadata. I fixed this which allows mapping/biom
files to be generated. The second problem is that someone uploaded new
metadata to the study and never reprocessed it, which is why you can't
generate PCoA plots. I'm re-processing the data now. Once that's done it
should work again.

On Fri, Sep 6, 2013 at 12:34 PM, Doug Wendel douginator2000@gmail.comwrote:

> It appears to be related to the ethnicity field. If you select all but
> that it generates a mapping file. Checking what the issue might be with
> that field now.
> 
> On Fri, Sep 6, 2013 at 12:20 PM, Doug Wendel douginator2000@gmail.comwrote:
> 
> > I can verify that Bobe_PGP fails. Any others?
> > 
> > On Fri, Sep 6, 2013 at 12:20 PM, Doug Wendel douginator2000@gmail.comwrote:
> > 
> > > Checking. Which studies were you working with?
> > > 
> > > On Fri, Sep 6, 2013 at 12:16 PM, Rob Knight notifications@github.comwrote:
> > > 
> > > > The web site is not working for me for meta-analysis right now (tried
> > > > both PCoA and taxonomy on different datasets; problem is that jobs don't
> > > > show up in the usual list, so not even the OTU table builds). Problem
> > > > started about 10 min ago when I got a "list index out of range" traceback
> > > > when trying to look at the PGP fecal data.
> > > > 
> > > > On Sep 6, 2013, at 12:10 PM, Doug Wendel <notifications@github.com
> > > > <mailto:notifications@github.com>> wrote:
> > > > 
> > > > All deployed on live - can you verify that it's working as expected?
> > > > 
> > > > On Wed, Sep 4, 2013 at 2:11 PM, Zech Xu <notifications@github.com
> > > > <mailto:notifications@github.com>> wrote:
> > > > 
> > > > > yup
> > > > > 
> > > > > On Wed, Sep 4, 2013 at 11:51 AM, Doug Wendel <
> > > > > notifications@github.commailto:notifications@github.com>wrote:
> > > > > 
> > > > > > Is this good to go? Everyone is satisfied it won't break stuff? :D
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23809688>
> > > > > > 
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23820148>
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Doug Wendel
> > > > Professional Research Associate
> > > > University of Colorado at Boulder
> > > > Department of Chemistry and Biochemistry, Knight Lab
> > > > 303-641-5442
> > > > wendel@colorado.edumailto:wendel@colorado.edu
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23958732>.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/498#issuecomment-23959151
> > > > .
> > > 
> > > ## 
> > > 
> > > Doug Wendel
> > > Professional Research Associate
> > > University of Colorado at Boulder
> > > Department of Chemistry and Biochemistry, Knight Lab
> > > 303-641-5442
> > > wendel@colorado.edu
> > 
> > ## 
> > 
> > Doug Wendel
> > Professional Research Associate
> > University of Colorado at Boulder
> > Department of Chemistry and Biochemistry, Knight Lab
> > 303-641-5442
> > wendel@colorado.edu
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edu

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edu

**Comment by rob-knight** [comment]
PGP and AG in various combinations.

On Sep 6, 2013, at 12:20 PM, "Doug Wendel" <notifications@github.com<mailto:notifications@github.com>> wrote:

Checking. Which studies were you working with?

On Fri, Sep 6, 2013 at 12:16 PM, Rob Knight <notifications@github.com<mailto:notifications@github.com>>wrote:

> The web site is not working for me for meta-analysis right now (tried both
> PCoA and taxonomy on different datasets; problem is that jobs don't show up
> in the usual list, so not even the OTU table builds). Problem started about
> 10 min ago when I got a "list index out of range" traceback when trying to
> look at the PGP fecal data.
> 
> On Sep 6, 2013, at 12:10 PM, Doug Wendel <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
> 
> All deployed on live - can you verify that it's working as expected?
> 
> On Wed, Sep 4, 2013 at 2:11 PM, Zech Xu <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
> 
> > yup
> > 
> > On Wed, Sep 4, 2013 at 11:51 AM, Doug Wendel <notifications@github.com<mailto:notifications@github.com>
> > mailto:notifications@github.com>wrote:
> > 
> > > Is this good to go? Everyone is satisfied it won't break stuff? :D
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23809688>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23820148>
> > .
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edumailto:wendel@colorado.edumailto:wendel@colorado.edu
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23958732>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/498#issuecomment-23959151
> .

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edumailto:wendel@colorado.edu

**Comment by rob-knight** [comment]
Ok thanks

On Sep 6, 2013, at 12:48 PM, "Doug Wendel" <notifications@github.com<mailto:notifications@github.com>> wrote:

Two issues appear to exist. One: There was some data in the ethnicity field
which contained invalid characters (i.e. line break) - probably a
copy/paste issue in the metadata. I fixed this which allows mapping/biom
files to be generated. The second problem is that someone uploaded new
metadata to the study and never reprocessed it, which is why you can't
generate PCoA plots. I'm re-processing the data now. Once that's done it
should work again.

On Fri, Sep 6, 2013 at 12:34 PM, Doug Wendel <douginator2000@gmail.com<mailto:douginator2000@gmail.com>>wrote:

> It appears to be related to the ethnicity field. If you select all but
> that it generates a mapping file. Checking what the issue might be with
> that field now.
> 
> On Fri, Sep 6, 2013 at 12:20 PM, Doug Wendel <douginator2000@gmail.com<mailto:douginator2000@gmail.com>>wrote:
> 
> > I can verify that Bobe_PGP fails. Any others?
> > 
> > On Fri, Sep 6, 2013 at 12:20 PM, Doug Wendel <douginator2000@gmail.com<mailto:douginator2000@gmail.com>>wrote:
> > 
> > > Checking. Which studies were you working with?
> > > 
> > > On Fri, Sep 6, 2013 at 12:16 PM, Rob Knight <notifications@github.com<mailto:notifications@github.com>>wrote:
> > > 
> > > > The web site is not working for me for meta-analysis right now (tried
> > > > both PCoA and taxonomy on different datasets; problem is that jobs don't
> > > > show up in the usual list, so not even the OTU table builds). Problem
> > > > started about 10 min ago when I got a "list index out of range" traceback
> > > > when trying to look at the PGP fecal data.
> > > > 
> > > > On Sep 6, 2013, at 12:10 PM, Doug Wendel <notifications@github.com<mailto:notifications@github.com>
> > > > mailto:notifications@github.com> wrote:
> > > > 
> > > > All deployed on live - can you verify that it's working as expected?
> > > > 
> > > > On Wed, Sep 4, 2013 at 2:11 PM, Zech Xu <notifications@github.com<mailto:notifications@github.com>
> > > > mailto:notifications@github.com> wrote:
> > > > 
> > > > > yup
> > > > > 
> > > > > On Wed, Sep 4, 2013 at 11:51 AM, Doug Wendel <
> > > > > notifications@github.commailto:notifications@github.commailto:notifications@github.com>wrote:
> > > > > 
> > > > > > Is this good to go? Everyone is satisfied it won't break stuff? :D
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23809688>
> > > > > > 
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23820148>
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Doug Wendel
> > > > Professional Research Associate
> > > > University of Colorado at Boulder
> > > > Department of Chemistry and Biochemistry, Knight Lab
> > > > 303-641-5442
> > > > wendel@colorado.edumailto:wendel@colorado.edumailto:wendel@colorado.edu
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/qiime/qiime_web_app/pull/498#issuecomment-23958732>.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHubhttps://github.com/qiime/qiime_web_app/pull/498#issuecomment-23959151
> > > > .
> > > 
> > > ## 
> > > 
> > > Doug Wendel
> > > Professional Research Associate
> > > University of Colorado at Boulder
> > > Department of Chemistry and Biochemistry, Knight Lab
> > > 303-641-5442
> > > wendel@colorado.edumailto:wendel@colorado.edu
> > 
> > ## 
> > 
> > Doug Wendel
> > Professional Research Associate
> > University of Colorado at Boulder
> > Department of Chemistry and Biochemistry, Knight Lab
> > 303-641-5442
> > wendel@colorado.edumailto:wendel@colorado.edu
> 
> ## 
> 
> Doug Wendel
> Professional Research Associate
> University of Colorado at Boulder
> Department of Chemistry and Biochemistry, Knight Lab
> 303-641-5442
> wendel@colorado.edumailto:wendel@colorado.edu

## 

Doug Wendel
Professional Research Associate
University of Colorado at Boulder
Department of Chemistry and Biochemistry, Knight Lab
303-641-5442
wendel@colorado.edumailto:wendel@colorado.edu

**Pull request merged**
